<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('country', function (Blueprint $table) {
            $table->id();
            $table->char('iso', 2)->nullable();
            $table->string('name', 80)->nullable();
            $table->string('nicename', 80)->nullable();
            $table->char('iso3', 3)->nullable();
            $table->smallInteger('numcode')->nullable();
            $table->integer('phonecode')->nullable();
        });

        $countries = [
            ['AF','AFGHANISTAN','Afghanistan','AFG',4,93],
            ['AL','ALBANIA','Albania','ALB',8,355],
            ['DZ','ALGERIA','Algeria','DZA',12,213],
            ['AS','AMERICAN SAMOA','American Samoa','ASM',16,1684],
            ['AD','ANDORRA','Andorra','AND',20,376],
            ['AO','ANGOLA','Angola','AGO',24,244],
            ['AI','ANGUILLA','Anguilla','AIA',660,1264],
            ['AG','ANTIGUA AND BARBUDA','Antigua and Barbuda','ATG',28,1268],
            ['AR','ARGENTINA','Argentina','ARG',32,54],
            ['AM','ARMENIA','Armenia','ARM',51,374],
            ['AW','ARUBA','Aruba','ABW',533,297],
            ['AU','AUSTRALIA','Australia','AUS',36,61],
            ['AT','AUSTRIA','Austria','AUT',40,43],
            ['AZ','AZERBAIJAN','Azerbaijan','AZE',31,994],
            ['BS','BAHAMAS','Bahamas','BHS',44,1242],
            ['BH','BAHRAIN','Bahrain','BHR',48,973],
            ['BD','BANGLADESH','Bangladesh','BGD',50,880],
            ['BB','BARBADOS','Barbados','BRB',52,1246],
            ['BY','BELARUS','Belarus','BLR',112,375],
            ['BE','BELGIUM','Belgium','BEL',56,32],
            ['BZ','BELIZE','Belize','BLZ',84,501],
            ['BJ','BENIN','Benin','BEN',204,229],
            ['BM','BERMUDA','Bermuda','BMU',60,1441],
            ['BT','BHUTAN','Bhutan','BTN',64,975],
            ['BO','BOLIVIA','Bolivia','BOL',68,591],
            ['BA','BOSNIA AND HERZEGOVINA','Bosnia and Herzegovina','BIH',70,387],
            ['BW','BOTSWANA','Botswana','BWA',72,267],
            ['BR','BRAZIL','Brazil','BRA',76,55],
            ['BN','BRUNEI DARUSSALAM','Brunei Darussalam','BRN',96,673],
            ['BG','BULGARIA','Bulgaria','BGR',100,359],
            ['BF','BURKINA FASO','Burkina Faso','BFA',854,226],
            ['BI','BURUNDI','Burundi','BDI',108,257],
            ['KH','CAMBODIA','Cambodia','KHM',116,855],
            ['CM','CAMEROON','Cameroon','CMR',120,237],
            ['CA','CANADA','Canada','CAN',124,1],
            ['CV','CAPE VERDE','Cape Verde','CPV',132,238],
            ['CF','CENTRAL AFRICAN REPUBLIC','Central African Republic','CAF',140,236],
            ['TD','CHAD','Chad','TCD',148,235],
            ['CL','CHILE','Chile','CHL',152,56],
            ['CN','CHINA','China','CHN',156,86],
            ['CO','COLOMBIA','Colombia','COL',170,57],
            ['KM','COMOROS','Comoros','COM',174,269],
            ['CG','CONGO','Congo','COG',178,242],
            ['CD','CONGO, THE DEMOCRATIC REPUBLIC OF THE','Congo, the Democratic Republic of the','COD',180,242],
            ['CK','COOK ISLANDS','Cook Islands','COK',184,682],
            ['CR','COSTA RICA','Costa Rica','CRI',188,506],
            ['HR','CROATIA','Croatia','HRV',191,385],
            ['CU','CUBA','Cuba','CUB',192,53],
            ['CY','CYPRUS','Cyprus','CYP',196,357],
            ['CZ','CZECH REPUBLIC','Czech Republic','CZE',203,420],
            ['DK','DENMARK','Denmark','DNK',208,45],
            ['DJ','DJIBOUTI','Djibouti','DJI',262,253],
            ['DM','DOMINICA','Dominica','DMA',212,1767],
            ['DO','DOMINICAN REPUBLIC','Dominican Republic','DOM',214,1809],
            ['EC','ECUADOR','Ecuador','ECU',218,593],
            ['EG','EGYPT','Egypt','EGY',818,20],
            ['SV','EL SALVADOR','El Salvador','SLV',222,503],
            ['GQ','EQUATORIAL GUINEA','Equatorial Guinea','GNQ',226,240],
            ['ER','ERITREA','Eritrea','ERI',232,291],
            ['EE','ESTONIA','Estonia','EST',233,372],
            ['ET','ETHIOPIA','Ethiopia','ETH',231,251],
            ['FO','FAROE ISLANDS','Faroe Islands','FRO',234,298],
            ['FJ','FIJI','Fiji','FJI',242,679],
            ['FI','FINLAND','Finland','FIN',246,358],
            ['FR','FRANCE','France','FRA',250,33],
            ['GA','GABON','Gabon','GAB',266,241],
            ['GM','GAMBIA','Gambia','GMB',270,220],
            ['GE','GEORGIA','Georgia','GEO',268,995],
            ['DE','GERMANY','Germany','DEU',276,49],
            ['GH','GHANA','Ghana','GHA',288,233],
            ['GI','GIBRALTAR','Gibraltar','GIB',292,350],
            ['GR','GREECE','Greece','GRC',300,30],
            ['GL','GREENLAND','Greenland','GRL',304,299],
            ['GD','GRENADA','Grenada','GRD',308,1473],
            ['GT','GUATEMALA','Guatemala','GTM',320,502],
            ['GN','GUINEA','Guinea','GIN',324,224],
            ['GW','GUINEA-BISSAU','Guinea-Bissau','GNB',624,245],
            ['GY','GUYANA','Guyana','GUY',328,592],
            ['HT','HAITI','Haiti','HTI',332,509],
            ['VA','HOLY SEE (VATICAN CITY STATE)','Holy See (Vatican City State)','VAT',336,39],
            ['HN','HONDURAS','Honduras','HND',340,504],
            ['HK','HONG KONG','Hong Kong','HKG',344,852],
            ['HU','HUNGARY','Hungary','HUN',348,36],
            ['IS','ICELAND','Iceland','ISL',352,354],
            ['IN','INDIA','India','IND',356,91],
            ['ID','INDONESIA','Indonesia','IDN',360,62],
            ['IR','IRAN, ISLAMIC REPUBLIC OF','Iran, Islamic Republic of','IRN',364,98],
            ['IQ','IRAQ','Iraq','IRQ',368,964],
            ['IE','IRELAND','Ireland','IRL',372,353],
            ['IL','ISRAEL','Israel','ISR',376,972],
            ['IT','ITALY','Italy','ITA',380,39],
            ['JM','JAMAICA','Jamaica','JAM',388,1876],
            ['JP','JAPAN','Japan','JPN',392,81],
            ['JO','JORDAN','Jordan','JOR',400,962],
            ['KZ','KAZAKHSTAN','Kazakhstan','KAZ',398,7],
            ['KE','KENYA','Kenya','KEN',404,254],
            ['KI','KIRIBATI','Kiribati','KIR',296,686],
            ['KW','KUWAIT','Kuwait','KWT',414,965],
            ['KG','KYRGYZSTAN','Kyrgyzstan','KGZ',417,996],
            ['LV','LATVIA','Latvia','LVA',428,371],
            ['LB','LEBANON','Lebanon','LBN',422,961],
            ['LS','LESOTHO','Lesotho','LSO',426,266],
            ['LR','LIBERIA','Liberia','LBR',430,231],
            ['LY','LIBYAN ARAB JAMAHIRIYA','Libyan Arab Jamahiriya','LBY',434,218],
            ['LI','LIECHTENSTEIN','Liechtenstein','LIE',438,423],
            ['LT','LITHUANIA','Lithuania','LTU',440,370],
            ['LU','LUXEMBOURG','Luxembourg','LUX',442,352],
            ['MO','MACAO','Macao','MAC',446,853],
            ['MG','MADAGASCAR','Madagascar','MDG',450,261],
            ['MW','MALAWI','Malawi','MWI',454,265],
            ['MY','MALAYSIA','Malaysia','MYS',458,60],
            ['MV','MALDIVES','Maldives','MDV',462,960],
            ['ML','MALI','Mali','MLI',466,223],
            ['MT','MALTA','Malta','MLT',470,356],
            ['MQ','MARTINIQUE','Martinique','MTQ',474,596],
            ['MR','MAURITANIA','Mauritania','MRT',478,222],
            ['MU','MAURITIUS','Mauritius','MUS',480,230],
            ['MX','MEXICO','Mexico','MEX',484,52],
            ['MD','MOLDOVA, REPUBLIC OF','Moldova, Republic of','MDA',498,373],
            ['MC','MONACO','Monaco','MCO',492,377],
            ['MN','MONGOLIA','Mongolia','MNG',496,976],
            ['MA','MOROCCO','Morocco','MAR',504,212],
            ['MZ','MOZAMBIQUE','Mozambique','MOZ',508,258],
            ['MM','MYANMAR','Myanmar','MMR',104,95],
            ['NA','NAMIBIA','Namibia','NAM',516,264],
            ['NP','NEPAL','Nepal','NPL',524,977],
            ['NL','NETHERLANDS','Netherlands','NLD',528,31],
            ['NZ','NEW ZEALAND','New Zealand','NZL',554,64],
            ['NI','NICARAGUA','Nicaragua','NIC',558,505],
            ['NE','NIGER','Niger','NER',562,227],
            ['NG','NIGERIA','Nigeria','NGA',566,234],
            ['NO','NORWAY','Norway','NOR',578,47],
            ['OM','OMAN','Oman','OMN',512,968],
            ['PK','PAKISTAN','Pakistan','PAK',586,92],
            ['PW','PALAU','Palau','PLW',585,680],
            ['PS','PALESTINIAN TERRITORY, OCCUPIED','Palestinian Territory, Occupied','PSE',275,970],
            ['PA','PANAMA','Panama','PAN',591,507],
            ['PG','PAPUA NEW GUINEA','Papua New Guinea','PNG',598,675],
            ['PY','PARAGUAY','Paraguay','PRY',600,595],
            ['PE','PERU','Peru','PER',604,51],
            ['PH','PHILIPPINES','Philippines','PHL',608,63],
            ['PL','POLAND','Poland','POL',616,48],
            ['PT','PORTUGAL','Portugal','PRT',620,351],
            ['PR','PUERTO RICO','Puerto Rico','PRI',630,1787],
            ['QA','QATAR','Qatar','QAT',634,974],
            ['RO','ROMANIA','Romania','ROU',642,40],
            ['RU','RUSSIAN FEDERATION','Russian Federation','RUS',643,7],
            ['RW','RWANDA','Rwanda','RWA',646,250],
            ['SA','SAUDI ARABIA','Saudi Arabia','SAU',682,966],
            ['SN','SENEGAL','Senegal','SEN',686,221],
            ['SC','SEYCHELLES','Seychelles','SYC',690,248],
            ['SL','SIERRA LEONE','Sierra Leone','SLE',694,232],
            ['SG','SINGAPORE','Singapore','SGP',702,65],
            ['SK','SLOVAKIA','Slovakia','SVK',703,421],
            ['SI','SLOVENIA','Slovenia','SVN',705,386],
            ['SO','SOMALIA','Somalia','SOM',706,252],
            ['ZA','SOUTH AFRICA','South Africa','ZAF',710,27],
            ['ES','SPAIN','Spain','ESP',724,34],
            ['LK','SRI LANKA','Sri Lanka','LKA',144,94],
            ['SD','SUDAN','Sudan','SDN',736,249],
            ['SR','SURINAME','Suriname','SUR',740,597],
            ['SZ','SWAZILAND','Swaziland','SWZ',748,268],
            ['SE','SWEDEN','Sweden','SWE',752,46],
            ['CH','SWITZERLAND','Switzerland','CHE',756,41],
            ['SY','SYRIAN ARAB REPUBLIC','Syrian Arab Republic','SYR',760,963],
            ['TW','TAIWAN, PROVINCE OF CHINA','Taiwan, Province of China','TWN',158,886],
            ['TJ','TAJIKISTAN','Tajikistan','TJK',762,992],
            ['TZ','TANZANIA, UNITED REPUBLIC OF','Tanzania, United Republic of','TZA',834,255],
            ['TH','THAILAND','Thailand','THA',764,66],
            ['TL','TIMOR-LESTE','Timor-Leste','TLS',626,670],
            ['TG','TOGO','Togo','TGO',768,228],
            ['TO','TONGA','Tonga','TON',776,676],
            ['TT','TRINIDAD AND TOBAGO','Trinidad and Tobago','TTO',780,1868],
            ['TN','TUNISIA','Tunisia','TUN',788,216],
            ['TR','TURKEY','Turkey','TUR',792,90],
            ['TM','TURKMENISTAN','Turkmenistan','TKM',795,7370],
            ['UG','UGANDA','Uganda','UGA',800,256],
            ['UA','UKRAINE','Ukraine','UKR',804,380],
            ['AE','UNITED ARAB EMIRATES','United Arab Emirates','ARE',784,971],
            ['GB','UNITED KINGDOM','United Kingdom','GBR',826,44],
            ['US','UNITED STATES','United States','USA',840,1],
            ['UY','URUGUAY','Uruguay','URY',858,598],
            ['UZ','UZBEKISTAN','Uzbekistan','UZB',860,998],
            ['VU','VANUATU','Vanuatu','VUT',548,678],
            ['VE','VENEZUELA','Venezuela','VEN',862,58],
            ['VN','VIET NAM','Viet Nam','VNM',704,84],
            ['YE','YEMEN','Yemen','YEM',887,967],
            ['ZM','ZAMBIA','Zambia','ZMB',894,260],
            ['ZW','ZIMBABWE','Zimbabwe','ZWE',716,263],
        ];

        foreach ($countries as $c) {
            DB::table('country')->insert([
                'iso'       => $c[0],
                'name'      => $c[1],
                'nicename'  => $c[2],
                'iso3'      => $c[3],
                'numcode'   => $c[4],
                'phonecode' => $c[5],
            ]);
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('country');
    }
};
